### ISSUE TITLE
Could not find matching constructor for: com.appthwack.AppThwackServer(...)

### ISSUE THREAD

**Issue by snowpong** [appthwack/gradle-plugin#5]
Hi

Using latest Android Studio (1.1) and `com.android.tools.build:gradle:1.1.0` I'm getting an error when syncing my build.gradle files:

> Error:(2, 0) Could not find matching constructor for: com.appthwack.AppThwackServer(com.appthwack.AppThwackExtension_Decorated, org.gradle.api.logging.Logging$LoggerImpl)

The backtrace says the following:

> Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.appthwack.AppThwackServer(com.appthwack.AppThwackExtension_Decorated, org.gradle.api.logging.Logging$LoggerImpl)
        at com.appthwack.AppThwackPlugin.apply(AppThwackPlugin.groovy:40)
        at com.appthwack.AppThwackPlugin.apply(AppThwackPlugin.groovy)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
        ... 44 more

My guess is something in groovy has changed since your plugin was written.
Here are the lines from around AppThwackPlugin.groovy:40:

>      29     @Override
     30     void apply(Project project) {
     31
     32         if (!project.plugins.hasPlugin('android') &&
     33                 !project.plugins.hasPlugin('android-library')) {
     34             throw new GradleException('The android or android-library has not been applied yet')
     35         }
     36
     37         extension = project.extensions.create(PLUGIN_NAME, AppThwackExtension)
     38
     39         project.android.testServer(
     40                 new AppThwackServer(extension, project.android.logger))
     41     }
     42 }

**Comment by piront** [comment]
I had the same issue last week. 

In order to get a successful build I changed the following :
        classpath 'com.android.tools.build:gradle:1.1.+'
to
        classpath 'com.android.tools.build:gradle:1.0.0'

**Comment by snowpong** [comment]
@piront Indeed that fixed the issue! Thanks for reaching out to me.

Note: I did not have to include `jersey-core` to make this work.

I suggest you (AppThwack) give a little TLC to this plugin and maybe release a 1.4?
I'd love to help but I honestly don't know how to build and debug gradle plugins :D

**Comment by twelve17** [comment]
@jkohls created a PR for this issue here: https://github.com/appthwack/gradle-plugin/issues/5 .  I [have added](https://github.com/appthwack/gradle-plugin/pull/4#issuecomment-86950152) instructions on how to build his version of the plugin, so you don't have to wait for the apptwhack team to release a version with the PR.
